version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5001:5000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge